export const ROUTES = {
  HOME: "/",
  AUTH: "/auth",
  BOOK: "/book",
  CONTACT: "/contact",
  COOKIES: "/cookies",
  DOCUMENTATION: "/documentation",
  DROP_OFF: "/drop-off",
  FAQ: "/faq",
  FOLLOW: "/follow",
  HISTORY: "/history",
  JOBS: "/jobs",
  LIST: "/list",
  PROFILE: "/profile",
  SCHEDULE: "/schedule",
  SETTING: "/setting",
  TERMS_AND_PRIVACY: "/terms-and-privacy",
  TOS: "/tos",
};
